import '../style1.css';
export default function Flu(){
    return(
      <main className="post">
      <div className="post-bg-wrapper">
      <div className="post-bg"></div></div>
      <div className="post-content">
          <h3 className="title">What is cat flu and how is it managed?</h3>
          <p className="textt">Cat flu is a general term for a highly contagious upper respiratory disease that affects cats and kittens. This disease is caused by one or more viruses including Feline Herpes Virus 1 (FHV1) and Feline Calicivirus (FVC). These viruses produces symptoms similar to the common cold in humans. Symptoms include sneezing, discharge from the eyes or nose, fever, breathing problems, coughing, fatigue and loss of appetite. Cats can also develop ulcers on the mouth or eyes. If the condition becomes severe and is not treated, it can cause permanent eye damage, pneumonia or even death. Kittens and older cats are the worst affected due to lower immunity.</p>
          <p className="textt">Cat flu is generally spread by direct contact between cats (through saliva, tears or nasal discharge), but it can also be spread indirectly, such as via food bowls, bedding, litter trays or human hands. It cannot be caught by humans or other animals. Affected cats can be severely debilitated. It is therefore vital that all kittens be vaccinated against the viruses that cause cat flu. Vaccination courses should start at 8 weeks of age, and booster vaccinations should be given as often as recommended by a veterinarian. Kittens need to be kept indoors and away from other cats until they are fully protected. Vaccination can prevent disease or reduce the severity of symptoms in those cats who become ill. Any cats who are sick with cat flu must be isolated from other cats until they are fully recovered. Their food bowls, litter trays and bedding must also be washed separately. Recovery typically takes around two weeks.</p>
          <p className="textt">As cat flu is caused by viruses, there is no direct cure, so treatment aims to relieve clinical signs until the immune system can clear the infection. Supportive treatment can include pain medication, anti-viral medication, eye drops and antibiotics for any secondary bacterial infection. Some cats need to be hospitalised and placed on an intravenous drip or given nutritional support if they stop eating and drinking. After recovering from cat flu, many cats will remain life-long carriers of the virus but will show no, or minimal, signs of the illness. Cats who are life-long carriers can spread the virus to others, as they sometimes ‘shed’ the virus during periods of stress such as boarding or entering a shelter. If you suspect your cat has cat flu, seek veterinary advice. In addition to medications, you can help your cat recover with nursing care. Nursing care can include steam inhalation to assist with breathing (e.g. via use of a humidifier), gentle bathing the eyes and nose with warm water to remove crusting and warming up strong smelling foods to tempt your cat to eat.</p>
      </div>
  </main>
          );
        }